### ISSUE TITLE
Device report: TERPORT TR95

### ISSUE THREAD

**Issue by Darko7z** [carlossless/sinowealth-kb-tool#13]
TERPORT TR95 uses BYK916 chip, the ids are different from nuphy-air60
Bootloader MD5: 2d169670eae0d36eae8188562c1f66e8
I haven't tried writing the firmware

pub const PART_TERPORT_TR95: Part = Part {
    flash_size: 61440, // 61440 until bootloader
    bootloader_size: 4096,
    page_size: 2048,
    vendor_id: 0x258a,
    product_id: 0x0049,
};

**Comment by carlossless** [comment]
Thank you!
