### ISSUE TITLE
[device-report] RK68 ISO Return

### ISSUE THREAD

**Issue by DramaTisxh** [carlossless/sinowealth-kb-tool#15]
_Sorry if this is useless information_

I think it can't go into isp mode for whatever reason.
Since I'm not really into all the stuff you did I have no idea what can be done😥

(I saw a few people wanting qmk on their rk keyboards with the BYK916 - including me - and I didn't find a way to do it so I thought your project is the closest there is to it, yet I'm stuck again)
_I just want to have layers on my keyboard without needing any software☹️_

pub const PART_RK_68_ISO_RETURN: Part = Part {
    flash_size: ?,
    bootloader_size: ?,
    page_size: ?,
    vendor_id: 0x258a,
    product_id: 0x00a9,
};

**Comment by carlossless** [comment]
@DramaTisxh have you confirmed that this keyboard is based on a BYK916? I saw that other RK keyboards like some versions of the RK61 are based on a [BYK916/SH68F90](https://www.reddit.com/r/MechanicalKeyboards/comments/r5vkzg/comment/johkwpl/?utm_source=share&utm_medium=web2x&context=3), but no mention of RK68.

In case it is a BYK916, I'm working on a custom (qmk-like) firmware for keyboards that are based on SH68F90/SH68F90A in https://github.com/carlossless/sh68f90a-experiments, although my initial aim is to only support the [nuphy-air60 v1](https://nuphy.com/products/air60) which I own myself.

**Comment by carlossless** [comment]
@DramaTisxh can you share the logs you get from trying to run `sinowealth-kb-tool` on your device?

It's possible that your device doesn't have an ISP bootloader or uses a different method to boot into it. We would need to look at a full dump of the firmware to make sure. If you have an arduino handy and comfortable wiring up JTAG pins you could try using https://github.com/gashtaan/sinowealth-8051-dumper to get that dump.

**Comment by carlossless** [comment]
Yep, nothing unusual about the logs. Let me know if you can manage to get a firmware dump from your device!

**Comment by carlossless** [comment]
@DramaTisxh I believe I fixed the issue that you were facing in #26. Would you mind giving it another try with the latest version of this tool?

**Comment by carlossless** [comment]
@DramaTisxh great! Can you please read the bootloader with `--bootloader` and share the MD5 (checksum) value?

**Comment by Dregu** [comment]
I stumbled here hoping to make my `ANSI RK68/855 white led 2021/02/26 REV:01` useful some day, cause the stock firmware is so bad I can't use if for anything.

This tool works well. I dumped backups, flashed the completely wrong smk version cause I was feeling brave and this kb is already dead to me. It blinded me, some keys worked, but matrix was obviously completely wrong, restored backup, didn't brick anything.

The bootloader for this ANSI version is `cfc8661da8c9d7e351b36c0a763426aa`, chip `BYK901`, vendor `258a`, product `008b`.

I have no idea how to make an smk layout for this, but I hope someone will some day.

**Comment by carlossless** [comment]
Thanks for the report @Dregu!

As a sidenote - I just came to realize how many different versions of RK68 actually exist out there. This list [rangoli](https://github.com/rnayabed/rangoli/blob/e1947210650c07727cc375b7637016055b481dfc/supported-keyboards.md) is very useful.

> I have no idea how to make an smk layout for this, but I hope someone will some day.

It's actually just a matter of figuring out which rows and columns of the key matrix (and led matrix) are connected to which pins on the MCU.

It should be doable with at least an understanding of basic eletronics (diodes, transistors, PWM led control) and a multimeter with a continuity test function.
