### ISSUE TITLE
Device report: NuPhy Halo65

### ISSUE THREAD

**Issue by mishamyrt** [carlossless/sinowealth-kb-tool#2]
Thank you very much for your work. This is not a real issue, rather I just want to pass on to you the information that the utility works with Halo 65. Compiled and was able to dump the firmware using the `nuphy-air60` part.

**Comment by carlossless** [comment]
@mishamyrt thanks a lot for reporting this!

Would you mind sharing the md5sum for your Halo 65 bootloader? Latest master will now print it out with every read operation, just use:
```sh
sinowealth-kb-tool read -p nuphy-air60 -b bootloader.hex
# should print "MD5: ..."
```
