### ISSUE TITLE
[device-report] Redragon Fizz K617-RGB

### ISSUE THREAD

**Issue by Xieyt** [carlossless/sinowealth-kb-tool#21]
The config is same as **TERPORT_TR95** including **VID** and **PID**.
Even the Bootloader hash is also same.
```
pub const PART_FIZZ_K617: Part = Part {
    flash_size: 61440, // 61440 until bootloader
    bootloader_size: 4096,
    page_size: 2048,
    vendor_id: 0x258a,
    product_id: 0x0049,
};
```
**Bootloader MD5**: `2d169670eae0d36eae8188562c1f66e8`

I haven't tried write operations on the keyboard.

**Comment by Xieyt** [comment]
I am not able to understand the Fizz is 60 % keyboard and TERPORT_TR95 is full size keyboard. Why they have same size booloader hash ? :thinking:

**Comment by carlossless** [comment]
@Xieyt Thanks for the report!

> I am not able to understand the Fizz is 60 % keyboard and TERPORT_TR95 is full size keyboard. Why they have same size booloader hash ? 🤔

The bootloader doesn't rely on much hardware other than ldo, clock and USB which are all fixed for SH68F90. That's why the exact same bootloader can be used irrespective of how the external hardware of these various keyboards is connected together.
