### ISSUE TITLE
[device-report] Royal Kludge RK 61 rgb wired 2022

### ISSUE THREAD

**Issue by timaxur** [carlossless/sinowealth-kb-tool#37]
## Device Info

- Sinowealth Device: `SH68F90?`
- IC Label: `BYK916`
- Product Page:  can't find the official product page for this version (wired rgb), here is the amazon page where I bought it https://www.amazon.com/RK-ROYAL-KLUDGE-Ultra-Compact-Switch-White/dp/B0832CZNS5/ . The pcb is labeled "130-81802-10 US   2022/08/16". There seem to be at least 2 HW versions of this keyboard using the same product name: there is also a 2019 edition that uses rebranded SN32F248BF MCU (https://github.com/euwbah/rk61-rgb-sonixqmk-firmware).

## Part Info

```
firmware_size: 61440
vendor_id: 0x258a
product_id: 0x00c7
bootloader_size: 4096 # necessary if not default
page_size: 2048 # necessary if not default
isp_usage_page and other isp options were not used
```

## Operations Tested

- [ X] Read
- [ X] Write

## Platforms Tested

- [ X] linux

## Checksums

- Bootloader MD5: `3e0ebd0c440af5236d7ff8872343f85d`
- Stock Firmware MD5: `0e2019195dac58e1463bf9c458db913a`

## HID Dump

A dump from usbhid-dump --model=0x258a

<details>
<summary>HID Tool Output</summary>

~~~

001:025:001:DESCRIPTOR         1704352530.015456
 05 01 09 80 A1 01 85 01 19 81 29 83 15 00 25 01
 75 01 95 03 81 02 95 05 81 01 C0 05 0C 09 01 A1
 01 85 02 19 00 2A 3C 02 15 00 26 3C 02 75 10 95
 01 81 02 C0 06 00 FF 09 01 A1 01 85 05 19 01 29
 02 15 00 26 FF 00 75 08 95 05 81 02 C0 05 01 09
 06 A1 01 85 06 05 07 19 04 29 70 15 00 25 01 75
 01 95 78 81 02 C0

001:025:000:DESCRIPTOR         1704352530.026447
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 75 08 95 01 81 01 05 07 19 00
 29 FF 15 00 26 FF 00 75 08 95 06 81 00 05 08 19
 01 29 05 15 00 25 01 75 01 95 05 91 02 75 03 95
 01 91 01 C0

~~~

</details>

**Comment by carlossless** [comment]
@timaxur thanks a lot for the report (and the additional info about revisions of this keyboard using the sonix mcu)
