### ISSUE TITLE
[Question] Redragon Shaco Pro (k641 pro)

### ISSUE THREAD

**Issue by Danial-Movahed** [carlossless/sinowealth-kb-tool#49]
## Device Info

- Sinowealth Device: SH68F90A
- IC Label: BYK916
- Product Page: https://redragonshop.com/products/shaco-k641-aluminum-wireless-keyboard

## Part Info

```
firmware_size: 61440
vendor_id: 0x258a
product_id: 0x0049
bootloader_size: 4096 # necessary if not default
page_size: 2048 # necessary if not default
isp_usage_page: 0xff00 # necessary if not default
isp_usage: 0x0001 # necessary if not default
isp_index: 0 # necessary if not default
```

## Operations Tested

- [ ] Read
- [ ] Write

## Platforms Tested

- [x] linux
- [ ] macos
- [ ] windows

## Checksums

- Bootloader MD5: `3e0ebd0c440af5236d7ff8872343f85d`
- Stock Firmware MD5: `idonthave`

## HID Dump
I don't have, But I have [wireshark](https://drive.google.com/file/d/1T7YeRrzZs_mTEANAlDOL-RlvJi6CWfh2/view?usp=sharing) capture of changing the modes from the software before it bricked.

##
Hello. This is not an issue, I just have a question. Sorry if it is stupid. I have a redragon shaco pro (k641 pro) keyboard and while I was trying to reverse engineer the rgb protocol, I have bricked its firmware and it is not detected by linux or windows anymore. It says 
device descriptor read/64, error -71.
I don't have any backups. Is there any way to put it into ISP Mode and flash smk on it with this tool? I tried using this tool 
https://github.com/gashtaan/sinowealth-fw-disabler
But nothing happened. I tried to manually flash smk with arduino and jtag on it by modifying https://github.com/gashtaan/sinowealth-8051-bl-updater data and address but after I flashed it when I plugged it in, the leds just blinked for a moment and descriptor read error came. I got a dump with https://github.com/gashtaan/sinowealth-8051-dumper and it shows all zeros after 0x0fff until the last 4096 bytes which is the bootloader. [My manual flash file](https://github.com/carlossless/sinowealth-kb-tool/files/14600014/SMKAddedWithbl.txt) and [dump after flashing it](https://github.com/carlossless/sinowealth-kb-tool/files/14600016/aftersmkwrite.txt) are attached. It looked like that 0xeffd also was flashed wrong but when I tried to reflash that byte I somehow made it worse. Now the entire 0xeff0 - 0xefff looks like this
8093BA0108955D983AE03A97F1F700C0
But the bootloader is intact.

BTW, Thanks very much for the nice tool and nice firmware, I'm sure they are very useful.

**Comment by Danial-Movahed** [comment]
I was able to my keyboard with these steps, maybe it'll help someone.
After some searching I found this:
[K916.998.NEW.B10.00.zip](https://github.com/swiftgeek/hykker-re/files/12255805/K916.998.NEW.B10.00.zip)
From
https://github.com/swiftgeek/hykker-re/issues/4

I built the code in k916 repository and flashed it manually with arduino and jtag with 4096 bytes steps and it got detected by linux and then I used this tool to flash smk on it and it worked.

**Comment by RILuse** [comment]
> I was able to my keyboard with these steps, maybe it'll help someone. After some searching I found this: [K916.998.NEW.B10.00.zip](https://github.com/swiftgeek/hykker-re/files/12255805/K916.998.NEW.B10.00.zip) From [swiftgeek/hykker-re#4](https://github.com/swiftgeek/hykker-re/issues/4)
> 
> I built the code in k916 repository and flashed it manually with arduino and jtag with 4096 bytes steps and it got detected by linux and then I used this tool to flash smk on it and it worked.

hello can you write step by step guide pls. i have a same problem with my keyboard... how to flash it back?
