### ISSUE TITLE
[device-report] Trust GXT 960

### ISSUE THREAD

**Issue by crashniels** [carlossless/sinowealth-kb-tool#52]
## Device Info

- Sinowealth Device: _`unknown`_
- IC Label: _`BY8801`_
- Product Page: _https://www.trust.com/de/product/23758-gxt-960-graphin-ultra-lightweight-gaming-mouse_

## Part Info

```
firmware_size: 61440
vendor_id: 0x145f
product_id: 0x02b6
bootloader_size: 4096 # necessary if not default
page_size: 2048 # necessary if not default
isp_usage_page: 0xff00 # necessary if not default
isp_usage: 0x0001 # necessary if not default
isp_index: 0 # necessary if not default
```

## Operations Tested

- [x] Read
- [ ] Write

## Platforms Tested

- [x] linux
- [ ] macos
- [ ] windows

## Checksums

- Bootloader MD5: `620f0b67a91f7f74151bc5be745b7110`
- Stock Firmware MD5: `95fe8060ab83c8bf9eee6d5cbc86652d`

## HID Dump

A dump from [usbhid-dump](https://github.com/DIGImend/usbhid-dump), [win-hid-dump](https://github.com/todbot/win-hid-dump) or [mac-hid-dump](https://github.com/todbot/mac-hid-dump)

<details>
<summary>HID Tool Output</summary>

```

003:011:001:DESCRIPTOR         1711043111.675525
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 95 06 75 08 15 00 26 FF
 00 05 07 19 00 2A FF 00 81 00 C0 06 0C 00 09 01
 A1 01 85 02 25 01 15 00 75 01 0A B5 00 0A B6 00
 0A B7 00 0A CD 00 0A E2 00 0A A2 00 0A E9 00 0A
 EA 00 95 08 81 03 0A 83 01 0A 94 01 0A 86 01 0A
 88 01 0A 8A 01 0A 92 01 0A A8 02 0A 84 01 95 08
 81 03 0A 21 02 0A 23 02 0A 24 02 0A 25 02 0A 26
 02 0A 27 02 0A 2A 02 0A B1 02 95 08 81 03 C0 06
 00 FF 09 01 A1 01 85 04 15 00 26 FF 00 09 00 75
 08 96 07 02 B1 02 C0 06 00 FF 09 01 A1 01 85 07
 15 00 26 FF 00 09 00 75 08 95 07 81 00 C0 06 00
 FF 09 01 A1 01 85 05 15 00 26 FF 00 09 00 95 05
 75 08 B1 02 C0

003:011:000:DESCRIPTOR         1711043111.678519
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 95 03 81 01 05 01
 09 30 09 31 16 00 80 26 FF 7F 75 10 95 02 81 06
 09 38 15 80 25 7F 75 08 95 01 81 06 05 0C 0A 38
 02 95 01 81 06 C0 C0

```

</details>

I ran 

```
sudo ./sinowealth-kb-tool read \
                 --vendor_id 0x145f \
                 --product_id 0x02b6 \
                 --firmware_size 61440 \
                 --bootloader_size 4096 \
                 --page_size 2048 \
                 --isp_iface_num 1 \
                 --isp_usage_page 0xff00 \
                 --isp_usage 0x0001 \
                 --isp_index 0 \
                 --reboot false \
                 foobar.hex
```

**Comment by carlossless** [comment]
I was curious about the MCU so I acquired it for research...

Unfortunately, unlike the [Glorious Model O](https://github.com/carlossless/sinowealth-kb-tool/issues/53), this one didn't have any visible JTAG header, and which MCU pins are JTAG ones is unclear to me too...

![trust-gxt-960-side Large](https://github.com/carlossless/sinowealth-kb-tool/assets/498906/27cf6b10-4392-4383-8d4e-cd9fcb7c6056)
![trust-gxt-960-side-2 Large](https://github.com/carlossless/sinowealth-kb-tool/assets/498906/5c82449b-19fe-437c-b49a-a718ddf29e47)
![trust-gxt-960-top Large](https://github.com/carlossless/sinowealth-kb-tool/assets/498906/f0ac1400-e72e-411f-b97c-216ca2262bcf)
![trust-gxt-960-bottom Large](https://github.com/carlossless/sinowealth-kb-tool/assets/498906/2db7d955-44e4-4084-b735-270cbc0e5572)
