### ISSUE TITLE
[device-report] Redragon DRACONIC K530 PRO

### ISSUE THREAD

**Issue by Danial-Movahed** [carlossless/sinowealth-kb-tool#60]
## Device Info

- Sinowealth Device: `SH68F90A`
- IC Label: `BYK916`
- Product Page: https://redragonshop.com/collections/redragon-mechanical-keyboard/products/mini-wireless-keyboard-draconic-k530

## Part Info

```
firmware_size: 61440
vendor_id: 0x258a
product_id: 0x0049
```

## Operations Tested

- [x] Read
- [x] Write

## Platforms Tested

- [x] linux
- [ ] macos
- [ ] windows

## Checksums

- Bootloader MD5: `cfc8661da8c9d7e351b36c0a763426aa`
- Stock Firmware MD5: `ec9caa25d6979e18919725ba449b81a4`

## HID Dump

A dump from [usbhid-dump](https://github.com/DIGImend/usbhid-dump), [win-hid-dump](https://github.com/todbot/win-hid-dump) or [mac-hid-dump](https://github.com/todbot/mac-hid-dump)

<details>
<summary>HID Tool Output</summary>

```
# Redragon DRACONIC K530 PRO using linux usbhid-dump
...
❯ sudo usbhid-dump -m 258a:0049
001:035:001:DESCRIPTOR         1712170898.477694
 05 01 09 80 A1 01 85 01 19 81 29 83 15 00 25 01
 75 01 95 03 81 02 95 05 81 01 C0 05 0C 09 01 A1
 01 85 02 19 00 2A 3C 02 15 00 26 3C 02 95 01 75
 10 81 00 C0 06 00 FF 09 01 A1 01 85 05 15 00 26
 FF 00 19 01 29 02 75 08 95 05 B1 02 C0 05 01 09
 06 A1 01 85 06 05 07 19 04 29 70 15 00 25 01 75
 01 95 78 81 02 C0 06 00 FF 09 01 A1 01 85 09 15
 00 26 FF 00 09 00 75 08 96 F8 01 B1 02 C0 06 00
 FF 09 01 A1 01 85 0A 15 00 26 FF 00 09 00 75 08
 95 29 B1 02 C0 06 00 FF 09 01 A1 01 85 0B 15 00
 26 FF 00 09 00 75 08 96 7A 01 B1 02 C0 05 01 09
 02 A1 01 85 0D 09 01 A1 00 05 09 15 00 25 01 19
 01 29 05 75 01 95 05 81 02 95 03 81 01 05 01 16
 00 80 26 FF 7F 09 30 09 31 75 10 95 02 81 06 15
 81 25 7F 09 38 75 08 95 01 81 06 05 0C 0A 38 02
 95 01 81 06 C0 C0 06 00 FF 09 01 A1 01 85 0C 15
 00 26 FF 00 09 00 75 08 96 80 07 B1 02 C0

001:035:000:DESCRIPTOR         1712170898.478814
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 95 08 75 01 81 02 95 01 75 08 81 03 95 06 75 08
 15 00 26 FF 00 05 07 19 00 2A FF 00 81 00 25 01
 95 05 75 01 05 08 19 01 29 05 91 02 95 01 75 03
 91 03 C0
```

</details>

Hi, I have got a bricked k530 and fixed it using my method that I used for my k641. This is the report of this tool. If you need any more info please let me know quickly because I have to return it in three days. Thx so much for the great tool.

**Comment by carlossless** [comment]
@Danial-Movahed thanks for the report! I believe the info provided is enough.
