### ISSUE TITLE
Air96 compatibility confirmed, tested dumping only.

### ISSUE THREAD

**Issue by WinkelCode** [carlossless/sinowealth-kb-tool#7]
Once again, bootloader MD5 as reported by the program is `3e0ebd0c440af5236d7ff8872343f85d`

Side note: MD5s for the rest of the FW is different between BT/USB mode.

**Comment by carlossless** [comment]
@WinkelCode thanks for the report! Are the pId and vId the same as with the other Air models?

**Comment by WinkelCode** [comment]
> @WinkelCode thanks for the report! Are the pId and vId the same as with the other Air models?

I believe so: 0x05AC 0x024F
