### ISSUE TITLE
[device-report] Leobog Hi75

### ISSUE THREAD

**Issue by Mooyeee** [carlossless/sinowealth-kb-tool#73]
## Device Info

- Sinowealth Device: `SH68F90A`
- IC Label: `BYK916`
- Product Page: https://leobogtech.com/products/leobog-hi75

## Part Info

```
firmware_size: 61440
vendor_id: 0x258a
product_id: 0x010c
isp_index: 1
```

## Operations Tested

- [x] Read
- [x] Write

## Platforms Tested

- [x] linux
- [ ] macos
- [x] windows

## Checksums

- Bootloader MD5: `3e0ebd0c440af5236d7ff8872343f85d`
- Stock Firmware MD5: `22c29eba2ce0ab1cfba5101e4a8a841b`
- Full (firmware + bootloader) MD5: `71c6416ad9f2a80920f9d59e5672893e`

## HID Dump

A dump from [usbhid-dump](https://github.com/DIGImend/usbhid-dump), [win-hid-dump](https://github.com/todbot/win-hid-dump) or [mac-hid-dump](https://github.com/todbot/mac-hid-dump)

<details>
<summary>HID Tool Output</summary>

```
# Leobog Hi75 using usbhid-dump
$ sudo usbhid-dump -m 258a:010c                                                                                                                                                                       
001:006:001:DESCRIPTOR         1714081999.287219
 06 01 00 09 80 A1 01 85 01 19 81 29 83 15 00 25
 01 95 03 75 01 81 02 95 01 75 05 81 01 C0 05 0C
 09 01 A1 01 85 02 19 00 2A FF 02 15 00 26 FF 7F
 95 01 75 10 81 00 C0 06 00 FF 09 01 A1 01 85 03
 15 00 26 FF 00 09 2F 75 08 95 03 81 02 C0 05 01
 09 06 A1 01 85 04 05 07 19 04 29 70 15 00 25 01
 75 01 95 78 81 02 C0 06 00 FF 09 01 A1 01 85 05
 15 00 26 FF 00 19 01 29 02 75 08 95 05 B1 02 C0
 06 00 FF 09 01 A1 01 85 06 15 00 26 FF 00 19 01
 29 02 75 08 96 07 02 B1 02 C0 05 01 09 02 A1 01
 85 07 09 01 A1 00 05 09 15 00 25 01 19 01 29 05
 75 01 95 05 81 02 95 03 81 01 05 01 16 00 80 26
 FF 7F 09 30 09 31 75 10 95 02 81 06 15 81 25 7F
 09 38 75 08 95 01 81 06 05 0C 0A 38 02 95 01 81
 06 C0 C0

001:006:000:DESCRIPTOR         1714081999.289246
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 95 08 75 01 81 02 95 01 75 08 81 03 95 06 75 08
 15 00 26 FF 00 05 07 19 00 2A FF 00 81 00 25 01
 95 05 75 01 05 08 19 01 29 05 91 02 95 01 75 03
 91 03 C0
```
</details>

Thanks for the nice work!
I was also able to flash smk on my Leobog Hi75 without bricking it, the firmware works but it's all over the place since I still need to figure out the layout, but the fact that works and I can revert by reflashing the backup is promising.

[leobog_hi75_backup_dumps.zip](https://github.com/carlossless/sinowealth-kb-tool/files/15122718/leobog_hi75_backup_dumps.zip)

**Comment by Baba-70** [comment]
@Mooyeee 
I am curious about whether you have the rgb or non-rgb version? The checksum for my firmware is different from the one you listed above. I am curious as to why these checksums differ.
